# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-promtail
  description: Promtail is an agent which ships the contents of local logs to a Loki instance
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

